require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VaultsController do

  # This should return the minimal set of attributes required to create a valid
  # Vault. As you add validations to Vault, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VaultsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:vault) { create :vault }
  before { controller.stub current_vault: vault }

  describe "GET index", pending: true do
    it "assigns all vaults as @vaults" do
      vault = Vault.create! valid_attributes
      get :index, {}, valid_session
      assigns(:vaults).should eq([vault])
    end
  end

  describe "GET show" do
    it "assigns the requested vault as @vault" do
      vault = Vault.create! valid_attributes
      get :show, {:id => vault.to_param}, valid_session
      assigns(:vault).should eq(vault)
    end
  end

  describe "GET new" do
    it "assigns a new vault as @vault" do
      get :new, {}, valid_session
      assigns(:vault).should be_a_new(Vault)
    end
  end

  describe "GET edit" do
    it "assigns the requested vault as @vault" do
      vault = Vault.create! valid_attributes
      get :edit, {:id => vault.to_param}, valid_session
      assigns(:vault).should eq(vault)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Vault" do
        expect {
          post :create, {:vault => valid_attributes}, valid_session
        }.to change(Vault, :count).by(1)
      end

      it "assigns a newly created vault as @vault" do
        post :create, {:vault => valid_attributes}, valid_session
        assigns(:vault).should be_a(Vault)
        assigns(:vault).should be_persisted
      end

      it "redirects to the created vault" do
        post :create, {:vault => valid_attributes}, valid_session
        response.should redirect_to(Vault.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved vault as @vault" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vault.any_instance.stub(:save).and_return(false)
        post :create, {:vault => { "name" => "invalid value" }}, valid_session
        assigns(:vault).should be_a_new(Vault)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Vault.any_instance.stub(:save).and_return(false)
        post :create, {:vault => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested vault" do
        vault = Vault.create! valid_attributes
        # Assuming there are no other vaults in the database, this
        # specifies that the Vault created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Vault.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => vault.to_param, :vault => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested vault as @vault" do
        vault = Vault.create! valid_attributes
        put :update, {:id => vault.to_param, :vault => valid_attributes}, valid_session
        assigns(:vault).should eq(vault)
      end

      it "redirects to the vault" do
        vault = Vault.create! valid_attributes
        put :update, {:id => vault.to_param, :vault => valid_attributes}, valid_session
        response.should redirect_to(vault)
      end
    end

    describe "with invalid params" do
      it "assigns the vault as @vault" do
        vault = Vault.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vault.any_instance.stub(:save).and_return(false)
        put :update, {:id => vault.to_param, :vault => { "name" => "invalid value" }}, valid_session
        assigns(:vault).should eq(vault)
      end

      it "re-renders the 'edit' template" do
        vault = Vault.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Vault.any_instance.stub(:save).and_return(false)
        put :update, {:id => vault.to_param, :vault => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested vault" do
      vault = Vault.create! valid_attributes
      expect {
        delete :destroy, {:id => vault.to_param}, valid_session
      }.to change(Vault, :count).by(-1)
    end

    it "redirects to the vaults list" do
      vault = Vault.create! valid_attributes
      delete :destroy, {:id => vault.to_param}, valid_session
      response.should redirect_to(vaults_url)
    end
  end

end
